### ISSUE TITLE
Structured HTML output? :)

### ISSUE THREAD

**Issue by rktic** [radusuciu/traktor_nowplaying#1]
Hey radusuciu,

this already is a great help - thank you very much!

Do you feel like implementing an option for structured HTML output? Like:

```
<dl>
<dt>artist</dt>
<dd>trackname</dd>
<dt>artist</dt>
<dd>trackname</dd>
<dt>artist</dt>
<dd>trackname</dd>
...
<dl>
```

It'd be a cracker for everyone streaming sets via OBS to style the output!

Cheers
Ronny

**Comment by radusuciu** [comment]
Hey Ronny, thanks for the feedback! I think I could implement this using a `--format` option to which you could pass something like: `<p><strong>{{ artist }}</strong> - {{ title }}</p>`, or any other simple template where you define use whatever markup you'd like around `{{ artist }}` and `{{ title }}`. This would output files that look like this:

```html
<p><strong>FakeArtist</strong> - FakeSong</p>
```

Would this be sufficient or does the resulting html file need to be fully valid (as below) and not just a fragment?
```html
<!DOCTYPE html>
<html>
  <body>
    <p><strong>FakeArtist</strong> - FakeSong</p>
  </body>
</html>
```

**Comment by rktic** [comment]
Hey,

thank you for the quick reply - custom formatting with passing an own structure would be even better! And I guess supplying a fully valid HTML file would make life even more easy for many users.

Looks like a winner to me!

**Comment by radusuciu** [comment]
@rktic So I've had some time while waiting for data processing tasks and put together a release that I think addresses what you've asked for here. I've made use of the template system from [Bottle](https://bottlepy.org/docs/0.12/stpl.html) and added two arguments: `--format` which can be used to change the format of individual tracks, and `--template` which gives you full control, including the ability to add markup around the listing. So for your example, you would create a `template.html` like this:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <dl>
      % for track in tracks:
      <dt>{{track.get('artist', '')}}</dt>
      <dd>{{track.get('title', '')}}</dd>
      % end
    </dl>
  </body>
</html>
```

Example command: `traktor_nowplaying -a -m 3 -t template.html -o nowplaying.html`. I opted against including a built-in HTML wrapper for now, but may include one later.

**Comment by rktic** [comment]
Wow - thank you very much!!!

**Comment by rktic** [comment]
Works like a charm and the templating is super useful! Finally proper styling options - YAY! <3

**Comment by radusuciu** [comment]
Awesome, glad to help!

**Comment by rktic** [comment]
Put it to good use already: https://www.twitch.tv/videos/737219428

**Comment by radusuciu** [comment]
Looks great! I see your list disappeared like 16 minutes in, any issues?

**Comment by rktic** [comment]
Yeah, it crashed - but I didn't log the error message, cause of being on-stream. I'll investigate and let you know once I know what's going on.
