### ISSUE TITLE
No output from traktor_nowplaying

### ISSUE THREAD

**Issue by hospitalit** [radusuciu/traktor_nowplaying#4]
Can not get any output from traktor_nowplaying. The nowplaying.txt remains empty. There is no output on the console. My Traktor Version is 3.4.1.254. This is a fresh install on windows 10. I tried it before on mac os. This did not work with the same configuration. I already tried the ports 9000, 8080 and 8001.
Is there anything wrong configured? Please see my screenshots.
Thank you!

![traktor_nowplaying no output (1)](https://user-images.githubusercontent.com/4559945/124526110-03cd0200-de02-11eb-8639-463d7bbf164f.jpg)
![traktor_nowplaying no output (2)](https://user-images.githubusercontent.com/4559945/124526111-04659880-de02-11eb-92d0-86df5f11caf1.jpg)
![traktor_nowplaying no output (3)](https://user-images.githubusercontent.com/4559945/124526113-04fe2f00-de02-11eb-899f-fa86772f28fb.jpg)
![traktor_nowplaying no output (4)](https://user-images.githubusercontent.com/4559945/124526115-04fe2f00-de02-11eb-8fb2-d78f954aea0e.jpg)

**Comment by radusuciu** [comment]
Hey, I can't tell from the screenshot but have you turned on the broadcast?

Also, I wouldn't be worried about the browser error page - you're not meant to be able to access it right now. Though I think I will add a message on that page saying this - thanks!

**Comment by hospitalit** [comment]
Yes. Thank you! I didn't see this little switch before. Now it works.
The small switch is located in the upper right corner of the mixer view.
![Traktor1](https://user-images.githubusercontent.com/4559945/124757788-3f64ea80-df2e-11eb-83cd-bbe27c6b9db3.jpg)
![Nowplaying1](https://user-images.githubusercontent.com/4559945/124757792-3ffd8100-df2e-11eb-8bff-58866bd4ca37.jpg)

**Comment by radusuciu** [comment]
Great, thanks for letting me know it works fine!
