### ISSUE TITLE
Traktor broadcasting to localhost now working

### ISSUE THREAD

**Issue by Lokixin** [radusuciu/traktor_nowplaying#5]
Hi! I am trying to use your python package to extract info from a song whenever it is changed in Traktor. I have configured the traktor broadcasting like you explain: address -> localhost and port-> 8000. Your library seems to work fine, however the broadcasting icon in traktor is continuously blinking. Do I need to provide any extra configuration parameters, such as the mount path or something like that? 

PD: Is possible to display in the template not only the artist and the title but the elapsed time for example?? Thanks a lot!
Thanks!

**Comment by radusuciu** [comment]
Hi there. The fact that the broadcasting icon is blinking means that the broadcast isn't hitting traktor_nowplaying. Could you share a screenshot of your traktor config and how you're running the traktor_nowplaying application? I can tell you if there's something wrong.

The elapsed time isn't easily possible unfortunately :/

**Comment by radusuciu** [comment]
Closing since no response - please feel free to ping me back!
