### ISSUE TITLE
Insert CRLF into --format?

### ISSUE THREAD

**Issue by DJFormica** [radusuciu/traktor_nowplaying#6]
Hi radusuciu,

I really appreciate this program, thank you. I am a Serato person but one of the DJs on my crew uses Traktor and we have a sign at the club which displays the track that is currently playing. I want to be able to support him and your program is the way to go 😀

One thing I have not yet figured out is how to insert escape characters (such as CRLF) into the --format command? I tried --format='{{artist}}\r\n{{title}}' but it just renders the text literally. This is on macOS Sierra if that makes a difference, but it will be writing to a Windows network location (thus the need for CRLF instead of just LF).

I guess another way to ask the question would be, what would be simplest way to get the output to be:

{{artist}}
{{title}}

With each variable on its own line? I figure there might be a way to do it with templates (since they don't have to be HTML) but I am dense and have not been able to figure that out yet either 🤔 The text is being picked up by OBS and rendered from there. I do eventually want to use HTML, but our gig is tomorrow night and redoing everything for HTML is not in scope for the next 18 hours 🤣🤣🤣

**Comment by radusuciu** [comment]
Hey! This may be a bug. I can take a look today and probably have a solution for you.

**Comment by DJFormica** [comment]
Thanks 😃 if I wanted to mock this (I don't have Traktor myself) will it work with any Ogg stream, basically? Can I just point it at an Icecast Ogg stream that has the proper metadata?

**Comment by radusuciu** [comment]
> Thanks 😃 if I wanted to mock this (I don't have Traktor myself) will it work with any Ogg stream, basically? Can I just point it at an Icecast Ogg stream that has the proper metadata?

Yeah it should

**Comment by radusuciu** [comment]
Try this as a template file:

```
% for track in tracks:
{{ track.get('artist', '') }}
{{ track.get('title', '') }}
% end
```

**Comment by radusuciu** [comment]
So I'm having some trouble replicating this, let me know if that template above works for you, if not, I suggest trying HTML:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
    </head>
    <body>
        % for track in tracks:
        <p>{{ track.get('artist', '') }}</p>
        <p>{{ track.get('title', '') }}</p>
        % end
    </body>
</html>
```

I know you said you're not looking to switch right before your gig but I think OBS should handle this pretty well out of the box - just point it to `tracklist.html` (or whatever you call it) instead of `tracklist.txt`.

I've got work now so won't be able to dig further for some time.

**Comment by DJFormica** [comment]
> So I'm having some trouble replicating this, let me know if that template above works for you, if not, I suggest trying HTML:
> 
> ```
> <!DOCTYPE html>
> <html>
>     <head>
>         <meta charset="UTF-8">
>     </head>
>     <body>
>         % for track in tracks:
>         <p>{{ track.get('artist', '') }}</p>
>         <p>{{ track.get('title', '') }}</p>
>         % end
>     </body>
> </html>
> ```
> 
> I know you said you're not looking to switch right before your gig but I think OBS should handle this pretty well out of the box - just point it to `tracklist.html` (or whatever you call it) instead of `tracklist.txt`.
> 
> I've got work now so won't be able to dig further for some time.

Thank you, I'm testing it with my friend now remotely. We'll try it at the club tonight. I'll let you know how it works. I really appreciate the help!

**Comment by DJFormica** [comment]
Thank you, the template.txt you provided worked! It correctly writes each element on a separate line. Probably a better mechanism than trying to figure out how to insert escape characters on the command line anyhow. Not sure if I'll have to mangle LF to CRLF or if OBS is smart enough to figure that out on its own, we'll see.

Incidentally, I wasn't able to get it to work with any combination of Icecast and an Ogg streaming client, although I only tried for a couple hours (it's a workday for me as well, plus getting ready for tonight's gig). I looked briefly at your new commit and will take a look at the rest of the code and see if I can figure out how to do so myself down the road.

I will send you a picture from the club of your work in action 😎

**Comment by radusuciu** [comment]
> Thank you, the template.txt you provided worked! It correctly writes each element on a separate line. Probably a better mechanism than trying to figure out how to insert escape characters on the command line anyhow. Not sure if I'll have to mangle LF to CRLF or if OBS is smart enough to figure that out on its own, we'll see.
> 
> Incidentally, I wasn't able to get it to work with any combination of Icecast and an Ogg streaming client, although I only tried for a couple hours (it's a workday for me as well, plus getting ready for tonight's gig). I looked briefly at your new commit and will take a look at the rest of the code and see if I can figure out how to do so myself down the road.
> 
> I will send you a picture from the club of your work in action 😎

Awesome!! have a good one!
