### ISSUE TITLE
Stop listening or execute code while listening

### ISSUE THREAD

**Issue by Scatti94** [radusuciu/traktor_nowplaying#8]
Is there a way to stop listening or execute code while listening? I'm fairly new to python and i can't seem to figure it out.

**Comment by Scatti94** [comment]
```
from traktor_nowplaying import Listener

listener = Listener(port=8000)
listener.start()
print("test")
```

when i execute this code it doesn't reach the print statement.

What i want to do is to start recording inside traktor and list all songs that are playing. When i end the recording i want my programm to rename the recorded file to all songtitles, so that i know what songs are in the mix.

**Comment by radusuciu** [comment]
Seems like this is solved, ping me again if not. Thanks!
